import { DataModel, Layer, ModelProperty, CodeValue, Language, SharedType } from './types';

export const i18n = {
  no: {
    appTitle: "GeoForge", 
    appSubtitle: "Fra data til tjeneste",
    newModel: "Ny modell", models: "Modeller", noModels: "Ingen modeller ennå",
    noModelsHint: "Opprett en ny modell for å komme i gang",
    landing: {
      title: "Hva vil du gjøre?",
      subtitle: "Velg utgangspunkt for å komme i gang",
      publishTitle: "Publiser data",
      publishDesc: "Last opp en GeoPackage og publiser med metadata. Rask vei fra fil til tjeneste.",
      publishDropHint: "Slipp en .gpkg-fil her",
      publishBrowse: "eller velg fil",
      modelTitle: "Jobb med modell",
      modelDesc: "Design eller importer en datamodell. For deg som vil ha full kontroll over struktur og felt.",
      modelNew: "Ny tom modell",
      modelImportFile: "Importer fil",
      modelImportGithub: "Hent fra GitHub",
      existingModels: "Eller fortsett med en eksisterende modell:",
      parsing: "Leser fil…",
    },
    quickPublish: {
      backToStart: "Tilbake til start",
      step1Title: "Vi fant dette i filen din",
      step1Desc: "Velg hvilke tabeller du vil publisere.",
      tableLabel: "Tabell",
      features: "features",
      columns: "kolonner",
      step2Title: "Beskriv datasettet",
      step2Desc: "Legg til metadata slik at andre kan finne og forstå dataene.",
      step3Title: "Publiser",
      step3Desc: "Push til GitHub for å starte deployment.",
      publishGuideTitle: "Hvordan fungerer publisering?",
      publishGuideSteps: [
        "Filene pushes til et GitHub-repo som du velger nedenfor.",
        "Hvis du publiserer til et repo som tilhører en annen (f.eks. Kartverket), opprettes det automatisk en pull request som må godkjennes før noe skjer.",
        "Når endringene er merget, bygges og deployes tjenesten automatisk via GitHub Actions.",
        "Du trenger et Personal Access Token (PAT) fra din egen GitHub-bruker. Hvis du skal levere til andre sitt repo, må de først gi din bruker skrivetilgang (collaborator). Opprett PAT under github.com → Settings → Developer settings."
      ],
      next: "Neste",
      back: "Tilbake",
      skipToPublish: "Hopp til publisering",
      editModel: "Vis full modell",
      selectedLayers: "tabeller valgt",
    },
    importGis: "Importer GIS-fil", importGisHint: "Velg en GeoJSON-, GML- eller GPKG-fil",
    importUrl: "Hent fra API (URL)", importUrlHint: "Lim inn en lenke til et GeoJSON REST-API",
    urlPlaceholder: "https://api.eksempel.no/data.geojson",
    fetchUrl: "Hent data", fetchError: "Kunne ikke hente data. Sjekk URL og CORS-innstillinger.",
    importGisError: "Kunne ikke lese filen. Sjekk at formatet er gyldig.",
    properties: "Egenskaper", addProperty: "Legg til felt", addSubProperty: "Legg til underfelt",
    sharedTypes: "Delte datatyper", addSharedType: "Ny datatype", sharedTypeName: "Typenavn",
    modelName: "Modellnavn", modelNamePlaceholder: "f.eks. Naturvernområder",
    descriptionPlaceholder: "Beskriv innholdet i dette datasettet...",
    sharedTypeDescriptionPlaceholder: "Beskriv hva denne datatypen brukes til (f.eks. felles adressefelt)...",
    namespace: "Navnerom", namespacePlaceholder: "f.eks. no.kommune.plan",
    version: "Versjon", cancel: "Avbryt", delete: "Slett",
    confirmDelete: "Er du sikker på at du vil slette denne modellen permanent?",
    confirmDeleteTitle: "Bekreft sletting",
    confirmDeleteBtn: "Ja, slett modell",
    undo: "Angre", redo: "Gjør om",
    layers: "Lag", addLayer: "Nytt lag", deleteLayer: "Slett lag",
    layerName: "Lagnavn", layerNamePlaceholder: "f.eks. Verneområder",
    geomColumnName: "Geometrikolonne",
    propName: "Teknisk navn", propNamePlaceholder: "f.eks. verneform",
    propTitle: "Visningsnavn", propTitlePlaceholder: "f.eks. Verneform",
    propType: "Datatype", propRequired: "Obligatorisk",
    propDefault: "Standardverdi",
    propDefaultPlaceholder: "f.eks. 0, 'Ukjent' eller true",
    propDescription: "Beskrivelse", propDescriptionPlaceholder: "Hva beskriver dette feltet?",
    propTargetLayer: "Mållag",
    propRelationType: "Relasjonstype",
    propCascadeDelete: "Kaskadesletting (slett automatisk ved sletting av mål)",
    deploy: {
      title: "Deploy",
      subtitle: "Koble til datakilde og generer deploy-pakke",
    },
    relationGroups: {
      standard: "Databasekobling",
      spatial: "Romlig kobling (autoberegnet)"
    },
    relationTypes: {
      foreign_key: "Fremmednøkkel (referanse via ID)",
      intersects: "Skjærer (overlapper)",
      contains: "Inneholder",
      within: "Ligger innenfor",
      touches: "Berører",
      crosses: "Krysser"
    },
    propCodelistMode: "Verdikilde",
    propCodelistModeInline: "Egne verdier",
    propCodelistModeExternal: "Ekstern URL",
    propCodelistUrl: "Kodeliste-URL", propCodelistUrlPlaceholder: "https://register.example.com/...",
    propGeometryType: "Geometritype",
    codelistValues: "Kodeverdier", addValue: "Legg til verdi",
    codeKey: "Kode", codeLabel: "Visningsnavn",
    codeDescription: "Beskrivelse (valgfri)",
    schemaPreview: "JSON Schema", copySchema: "Kopier", copied: "Kopiert!",
    noPropertiesYet: "Ingen egenskaper ennå",
    noPropertiesHint: "Legg til egenskaper for å beskrive laget",
    modelDetails: "Modelldetaljer", language: "Språk",
    unsavedChanges: "Ulagrede endringer",
    layerValidation: {
      title: "Valideringsregler",
      addRule: "Legg til regel",
      field1: "Felt 1",
      operator: "Operator",
      field2: "Felt 2",
      errorMessage: "Feilmelding",
      errorMessagePlaceholder: "f.eks. Sluttdato må være etter startdato",
      deleteRule: "Slett regel",
      noRules: "Ingen valideringsregler definert ennå."
    },
    visualTab: "Visning", schemaTab: "Schema", githubTab: "GitHub", exportTab: "Eksport", tutorialTab: "API",
    helpTab: "Hjelp",
    mappingTab: "Data Mapper",
    viewDiagram: "ER-diagram", viewCard: "Datakort",
    noPropsViz: "Legg til egenskaper for å se visualisering",
    moveUp: "Flytt opp", moveDown: "Flytt ned",
    crsLabel: "Koordinatsystem (CRS)",
    crsPlaceholder: "f.eks. EPSG:4326 eller EPSG:25833",
    tabs: { models: "Modeller", editor: "Rediger", preview: "Forhåndsvis" },
    review: {
      reviewChanges: "Se endringer",
      exitReview: "Avslutt gjennomgang",
      summaryTitle: "Endringsoversikt",
      changes: "endringer",
      added: "Lagt til",
      modified: "Endret",
      deleted: "Slettet",
      empty: "tom",
      addedCode: "Ny kode",
      deletedCode: "Slettet kode",
      breakingChanges: "Brytende endringer",
      newFeatures: "Ny funksjonalitet",
      improvementsFixes: "Forbedringer og feilrettinger",
      modelMetadata: "Modellmetadata",
      compareWith: "Sammenlign med…",
      noChanges: "Ingen endringer oppdaget.",
      reviewingChanges: "Gjennomgår endringer",
      totalOperations: "operasjoner oppdaget",
      layer: "Lag",
      field: "Felt",
      setting: "Innstilling",
      latestBaseline: "Siste publiserte versjon",
      reviewAndPublish: "Gjennomgå og publiser",
      vcs: "Versjonskontroll",
      currentVersion: "Gjeldende versjon",
      suggestedVersion: "Foreslått neste versjon",
      generatedChangelog: "Generert endringslogg",
      commitMessage: "Commit-melding",
      confirmAndPublish: "Bekreft og publiser",
      addedRule: "Ny regel",
      deletedRule: "Slettet regel",
      modifiedRuleLogic: "Endret regellogikk",
      rule: "Regel",
      errorMessage: "Feilmelding"
    },
    manual: {
      title: "Brukerveiledning",
      subtitle: "Lær hvordan du bruker GeoForge steg for steg.",
      step1Title: "1. Design og arkitektur",
      step1Desc: "Begynn med å definere lagene dine. Hvert lag tilsvarer en tabell. Legg til egenskaper og velg riktig datatype. Bruk «Kodeliste» for felt som skal ha forhåndsdefinerte valg – dette sikrer maskinlesbare og konsistente data.",
      step2Title: "2. Kvalitetssikring (restriksjoner)",
      step2Desc: "Klikk på skjold-ikonet ved en egenskap for å stille krav til dataene. Her kan du definere primærnøkler, tvinge unike verdier eller sette numeriske grenser (min/maks). Dette er grunnlaget for god datakvalitet.",
      step3Title: "3. GitHub og samarbeid",
      step3Desc: "Bruk GitHub-fanen for å lagre modellen din i et sentralt arkiv. Fordi modellene lagres som ren tekst (JSON), får du full versjonskontroll, endringshistorikk og mulighet til å bygge videre på andres arbeid.",
      step4Title: "4. Gjenbruk data med Data Mapper",
      step4Desc: "Har du allerede data i et annet format? Bruk Data Mapper (🔗). Last opp kildefilen og koble de gamle feltene til den nye modellen for å få et ferdig migrasjonsskript.",
      step5Title: "5. Symbologi og visualisering",
      step5Desc: "Under fanen «Symbologi» kan du sette farger og stiler. Med kategorisert visning kan du fargelegge dataene basert på kodelistene dine. Stilene følger automatisk med i eksportene.",
      step6Title: "6. Distribusjon (Deploy)",
      step6Desc: "Når modellen og dataene er klare, går du til fanen «Deploy». Velg datakilden din og last ned en ferdig pakke. Pakken inneholder Docker-oppsett som automatisk starter pygeoapi for moderne REST-tilgang, og QGIS Server for ferdig stylede WMS-kart."
    },
    mapper: {
      title: "Data Mapper (GDAL/OGR)",
      desc: "Migrer eksisterende data inn i den nye modellen for å sikre riktig format og høy kvalitet.",
      intro: "Flytt data fra eksisterende filer (GeoJSON, GeoPackage, GML) over til den nye datamodellen. Koble kildefelt til modellfelt, og generer et ferdig ogr2ogr-skript som utfører transformasjonen.",
      step1: "1. Last opp kilde",
      step2: "2. Velg tabeller",
      step3: "3. Koble felter",
      step4: "4. Generer skript",
      uploadSource: "Last opp kildefil",
      uploadUrl: "Lim inn API-URL",
      uploadHint: "GeoPackage, GML eller GeoJSON",
      selectSourceLayer: "Kildetabell",
      selectTargetLayer: "Mållag i modellen",
      sourceFields: "Kildefelter",
      targetFields: "Modellfelt",
      unmapped: "Ikke koblet",
      generateScript: "Generer skript",
      copyScript: "Kopier skript",
      scriptHint: "Skriptet bruker ogr2ogr til å transformere dataene.",
      sourceFilePlaceholder: "kildefil.gpkg",
      noFieldsFound: "Ingen felter funnet.",
      autoMap: "Autokoble",
      clear: "Nullstill",
      howToRun: "Hvordan kjøre skriptet?",
      howToRunDesc: "Når du er ferdig med feltmappingen, kopierer du kommandoen og kjører den i terminalen.",
      requirements: "Krever GDAL.",
      gdalLink: "GDAL-installasjon",
      multiLayerHint: "Du kan mappe flere lag i samme økt.",
      explanation: {
        title: "Forklaring",
        f: "-f GPKG: Lagrer som GeoPackage.",
        nln: "-nln: Angir tabellnavnet i utdatafilen.",
        nlt: "-nlt: Validerer og tvinger geometritypen.",
        sql: "-sql: Mapper gamle feltnavn til nye."
      },
      aboutGdal: {
        title: "Hva er GDAL/OGR?",
        desc: "GDAL/OGR er industristandarden for lesing og skriving av geodata. Dette verktøyet genererer et ogr2ogr-skript som lar deg flytte data sømløst mellom systemer uten tap av kvalitet."
      },
      mapValues: "Koble verdier",
      values: "verdier",
      keepValue: "— Behold opprinnelig verdi —",
      noPropsTarget: "Ingen egenskaper definert i mållaget.",
      mapOneHint: "Mapp minst ett lag for å se skriptet",
      dbMigration: "Databasemigrering",
      scalableArch: "Skalerbar arkitektur",
      simpleFileMig: "Enkel filmigrering",
      postgisAdvantage: "Migrering til PostGIS gir best ytelse for store datamengder og produksjonsmiljøer.",
      gpkgAdvantage: "GeoPackage er ideelt for arkivering og mindre prosjekter."
    },
    deploy: {
      title: "Deploy",
      subtitle: "Koble til datakilde og publiser tjenestekonfigurasjon",
      steps: ["Velg kilde", "Koble til", "Kartlegg lag", "Publiser"],
      sourceTitle: "Hvor ligger dataene som skal publiseres?",
      sources: {
        postgis: "Cloud SQL / PostGIS",
        postgisDesc: "Google Cloud SQL, Azure, AWS RDS, eller hvilken som helst PostgreSQL med PostGIS",
        supabase: "Supabase",
        supabaseDesc: "Koble til direkte via Supabase prosjekt-URL og API-nøkkel",
        databricks: "Databricks",
        databricksDesc: "Delta-tabeller via Databricks SQL Warehouse",
        geopackage: "Lokal GeoPackage",
        geopackageDesc: "Server data direkte fra en lokal .gpkg-fil uten behov for database",
      },
      connectionTitle: "Tilkoblingsdetaljer",
      fields: {
        host: "Host",
        port: "Port",
        database: "Database",
        user: "Bruker",
        password: "Passord",
        schema: "Schema",
        projectUrl: "Project URL",
        anonKey: "Anon Key",
        serverHostname: "Server Hostname",
        httpPath: "HTTP Path",
        accessToken: "Access Token",
        catalog: "Catalog",
      },
      supabaseHint: "Finn denne i Supabase Dashboard → Settings → API",
      mappingTitle: "Kartlegg lag til tabeller",
      mappingDesc: "Bekreft tabellnavn og velg timestamp-kolonne for endrings­sporing.",
      sourceTable: "Kildetabell",
      sourceTableHint: "Tabellnavnet slik det er i kildedatabasen",
      timestampColumn: "Timestamp-kolonne",
      timestampPlaceholder: "f.eks. sist_endret, updated_at",
      timestampHint: "Valgfritt. Uten denne spores kun nye og slettede features, ikke endringer i eksisterende.",
      primaryKeyColumn: "Primærnøkkel",
      primaryKeyHint: "Kolonne som unikt identifiserer hver rad. Standard: fid",
      fieldMapping: "Feltkobling",
      moreFields: "flere felt",
      // Step 3: Publish
      publishTitle: "Publiser til GitHub",
      publishDesc: "Push tjenestekonfigurasjon til et GitHub-repo. En CI/CD-pipeline tar seg av resten.",
      githubRepo: "Repository",
      githubRepoPlaceholder: "organisasjon/repo",
      githubRepoHint: "Eget repo for self-hosting, eller Kartverket sitt repo for vertskap",
      githubBranch: "Branch",
      githubToken: "Personal Access Token",
      githubTokenHint: "Trenger «repo»-rettighet",
      githubBasePath: "Mappesti i repo",
      githubBasePathPlaceholder: "tjenester/mitt-datasett",
      githubBasePathHint: "Valgfri undermappe. Tomt = rot i repoet.",
      repoChecking: "Sjekker tilgang…",
      repoAccessPR: "Du publiserer til {owner} sitt repo — endringene sendes som pull request for godkjenning.",
      repoAccessDirect: "Du har skrivetilgang — endringene pushes direkte til {branch}.",
      repoAccessError: "Kunne ikke verifisere tilgang. Sjekk repo og token.",
      gpkgFilename: "GeoPackage Filnavn",
      gpkgHint: "Plasser denne filen i ./data mappen",
      notConnected: "Ikke tilkoblet",
      timestampExplainer: "Velg kolonnen som lagrer endringstidspunkt (f.eks. 'updated_at'). Dette muliggjør inkrementell synkronisering (Delta), slik at bare endrede data eksporteres.",
      noTimestamp: "-- Ingen (Full eksport) --",
      publishBtn: "Publiser",
      publishing: "Publiserer…",
      publishSuccess: "Publisert!",
      publishError: "Publisering feilet",
      prCreated: "Pull request opprettet",
      prCreatedDesc: "En teknisk ansvarlig kan nå godkjenne og merge for å starte deployment.",
      directPushDesc: "Endringene er pushet. GitHub Actions vil starte deployment automatisk.",
      viewPR: "Åpne pull request",
      viewCommit: "Se commit",
      downloadZip: "Last ned som zip i stedet",
      // Shared
      kitTitle: "Deploy-konfigurasjon for",
      readyToGenerate: "Klar til å publisere",
      source: "Kilde",
      layersLabel: "Lag",
      changeTracking: "Endringssporing",
      changeTrackingAll: "Inserts + slettinger: alle lag",
      updatesLabel: "Oppdateringer",
      packageContents: "Filer som publiseres",
      files: {
        docker: "Starter pygeoapi + QGIS Server + delta-worker",
        dockerfile: "Container-image for pygeoapi",
        pygeoapi: "OGC API-konfigurasjon",
        pygeoapiPg: "PostgreSQL-tilkobling (live)",
        pygeoapiGpkg: "GeoPackage-fil (Databricks)",
        qgis: "QGIS-prosjekt med stil",
        delta: "Inkrementell eksport med slettestøtte",
        env: "Tilkoblingsdetaljer (ikke commit til git!)",
        model: "Modelldefinisjon (JSON)",
        workflow: "CI/CD-pipeline for automatisk deployment",
      },
      previewConfig: "Forhåndsvis pygeoapi-konfig",
      back: "Tilbake",
      next: "Neste",
    },
    metadata: {
      sectionTitle: "Metadata for publisering",
      sectionHint: "Strukturert metadata (GeoDCAT-AP) som følger med i tjenestekonfigurasjon og katalogregistrering.",
      contactName: "Kontaktperson",
      contactNamePlaceholder: "f.eks. Ola Nordmann",
      contactEmail: "E-post",
      contactEmailPlaceholder: "f.eks. ola@organisasjon.no",
      contactOrganization: "Utgiver",
      contactOrganizationPlaceholder: "f.eks. Miljødirektoratet",
      keywords: "Nøkkelord",
      keywordsPlaceholder: "Skriv nøkkelord og trykk Enter…",
      theme: "Tema (INSPIRE)",
      license: "Lisens",
      licenses: {
        'CC-BY-4.0': "CC BY 4.0 (Navngivelse)",
        'CC0-1.0': "CC0 1.0 (Ingen rettigheter)",
        'CC-BY-SA-4.0': "CC BY-SA 4.0 (Del på like vilkår)",
        'NLOD-2.0': "NLOD 2.0 (Norsk lisens for offentlige data)",
        'other': "Annen",
      },
      accessRights: "Tilgangsnivå",
      accessRightsOptions: {
        'public': "Offentlig",
        'restricted': "Begrenset",
        'non-public': "Ikke-offentlig",
      },
      purpose: "Formål",
      purposePlaceholder: "Beskriv formålet med datasettet…",
      accrualPeriodicity: "Oppdateringsfrekvens",
      frequencies: {
        'cont': "Kontinuerlig",
        'daily': "Daglig",
        'weekly': "Ukentlig",
        'monthly': "Månedlig",
        'quarterly': "Kvartalsvis",
        'annual': "Årlig",
        'asNeeded': "Etter behov",
        'irregular': "Uregelmessig",
        'unknown': "Ukjent",
      },
      spatialExtent: "Romlig utstrekning (bbox)",
      west: "Vest", east: "Øst", south: "Sør", north: "Nord",
      temporalExtent: "Tidsperiode",
      temporalFrom: "Fra",
      temporalTo: "Til",
      themes: {
        'ac': "Atmosfæriske forhold",
        'ad': "Adresser",
        'af': "Landbruk og akvakultur",
        'am': "Overvåkingsanlegg",
        'au': "Administrative enheter",
        'br': "Biogeografiske regioner",
        'bu': "Bygninger",
        'cp': "Eiendomsteiger (matrikkel)",
        'ef': "Miljøovervåkingsfasiliteter",
        'el': "Høydedata",
        'er': "Energiressurser",
        'ge': "Geologi",
        'gg': "Geografiske rutenett",
        'gn': "Stedsnavn",
        'hb': "Habitater og biotoper",
        'hh': "Menneskelig helse og sikkerhet",
        'hy': "Hydrografi",
        'lc': "Arealbruk",
        'lu': "Arealbruk (planlagt)",
        'mf': "Meteorologiske og oseanografiske forhold",
        'mr': "Mineralressurser",
        'nz': "Naturlige risikosoner",
        'of': "Oseanografiske forhold",
        'oi': "Ortofoto",
        'pd': "Befolkningsfordeling",
        'pf': "Produksjons- og industrianlegg",
        'ps': "Beskyttede områder",
        'rs': "Koordinatsystemer",
        'sd': "Artsfordeling",
        'so': "Jordsmonn",
        'sr': "Havområder",
        'ss': "Statistiske enheter",
        'su': "Nytteareal",
        'tn': "Transportnett",
        'us': "Allmennyttige og offentlige tjenester",
      },
    },
    constraints: {
      title: "Restriksjoner",
      min: "Minimumsverdi",
      max: "Maksimumsverdi",
      minLength: "Minimumslengde",
      maxLength: "Maksimumslengde",
      pattern: "Mønster (regex)",
      patternPlaceholder: "^[A-Z]{3}$",
      unique: "Unik",
      primaryKey: "Primærnøkkel",
      notNull: "Obligatorisk (NOT NULL)",
      enumeration: "Tillatte verdier",
      enumPlaceholder: "Skriv verdi og trykk Enter…"
    },
    styling: {
      title: "Symbologi",
      modeSimple: "Enkel farge",
      modeCategorized: "Kategorisert",
      pickColor: "Velg farge",
      selectProperty: "Velg felt for fargelegging",
      noCodelistProps: "Ingen kodelister funnet i dette laget.",
      colorsForValues: "Farge per verdi",
      followingModel: "Bruker modellens CRS:",
      pointSize: "Punktstørrelse (px)",
      pointIcon: "Symbol",
      lineWidth: "Linjebredde (px)",
      lineDash: "Linjestil",
      fillOpacity: "Gjennomsiktighet",
      hatchStyle: "Skravurmønster",
      hatchThickness: "Skravurtykkelse (px)",
      hatchSpacing: "Skravuravstand (px)",
      preview: "Forhåndsvisning",
      unitHint: "Alle størrelser er i piksler (px).",
      icons: { circle: "Sirkel", square: "Firkant", triangle: "Trekant", star: "Stjerne" },
      dashes: { 
        solid: "Heltrukket", 
        dashed: "Stiplet", 
        dotted: "Prikket",
        'dash-dot': "Strek-punkt",
        'dash-dot-dot': "Strek-punkt-punkt",
        'long-dash': "Lang strek"
      },
      hatches: {
        solid: "Heldekkende",
        horizontal: "Horisontale linjer",
        vertical: "Vertikale linjer",
        cross: "Rutenett",
        b_diagonal: "Diagonal (høyre)",
        f_diagonal: "Diagonal (venstre)",
        diagonal_x: "Diagonalt kryss"
      }
    },
    guide: {
      title: "Velkommen til GeoForge",
      subtitle: "Alt du trenger for å designe, kvalitetssikre og dele geodata.",
      close: "Kom i gang",
      sections: {
        modeling: "1. Design og modellering",
        modelingDesc: "Definer lagene dine og sett opp egenskaper med presise datatyper. Restriksjoner og kodelister sørger for at dataene holder høy kvalitet fra starten av.",
        mapping: "2. Data Mapper",
        mappingDesc: "Gjenbruk eksisterende data. Koble gamle kildefiler til den nye modellen og få ferdige migrasjonsskript basert på GDAL.",
        versioning: "3. GitHub og samarbeid",
        versioningDesc: "Modellene lagres som tekstfiler i GitHub. Det gir full endringshistorikk og gjør det enkelt å samarbeide på tvers av organisasjonen.",
        export: "4. Bygg struktur (Export)",
        exportDesc: "Bruk Eksport-fanen for å generere tabellstrukturer for databasen din (Cloud SQL, Databricks), tomme GeoPackage-maler og ryddig dokumentasjon.",
        api: "5. Publiser tjenester (Deploy)",
        apiDesc: "Når dataene er på plass, går du til Deploy-fanen. Velg datakilden din og få en ferdig Docker-pakke som automatisk starter pygeoapi (REST) og QGIS Server (WMS)!"
      }
    },
    github: {
      section: "GitHub-integrasjon",
      persistenceDesc: "Lagre modeller i et sentralt arkiv for full kontroll og historikk.",
      token: "Personal Access Token",
      tokenHint: "Påkrevd for å publisere endringer.",
      tokenHelp: "Hvordan oppretter jeg et token?",
      tokenPermissions: "Tokenet må ha rettigheten «repo» for å kunne skrive til arkivene dine. Dette trengs kun for å publisere endringer tilbake til GitHub.",
      repo: "Repository",
      repoPlaceholder: "eier/arkiv",
      branch: "Branch",
      path: "Filsti",
      pathPlaceholder: "modeller/skog.json",
      push: "Publiser til GitHub",
      pushing: "Publiserer…",
      pushed: "Publisert!",
      fetch: "Hent fra GitHub",
      fetching: "Henter…",
      fetched: "Hentet!",
      error: "GitHub-feil",
      importError: "Kunne ikke tolke filen fra GitHub. Sjekk at filstien er riktig.",
      noTokenWarn: "Du må legge inn et token for å kunne lagre endringer til GitHub.",
      commitMsg: "Commit-melding",
      commitSummary: "Sammendrag",
      commitMsgPlaceholder: "Beskriv endringene dine…",
      commitSummaryPlaceholder: "Kort tittel for endringen…",
      connecting: "Kobler til GitHub…",
      invalidToken: "Ugyldig token. Sjekk rettighetene.",
      repoNotFound: "Fant ikke repository eller filsti.",
      validationFailed: "Validering feilet. Er branchen riktig?",
      unknownError: "En uventet feil oppstod.",
      importTitle: "Importer fra GitHub",
      importBtn: "Hent modell"
    },
    doc: {
      title: "Dataspesifikasjon",
      layer: "Lag",
      tableHeader: { name: "Navn", type: "Type", req: "Obligatorisk", desc: "Beskrivelse" },
      yes: "Ja", no: "Nei"
    },
    types: { string: "Tekst", number: "Desimaltall", integer: "Heltall", boolean: "Ja/Nei", date: "Dato", geometry: "Geometri", codelist: "Kodeliste", json: "JSON", relation: "Relasjon", object: "Objekt (sammensatt)", array: "Liste", shared_type: "Delt datatype" },
    geometryTypes: { Point: "Punkt", LineString: "Linje", Polygon: "Flate", MultiPoint: "Multipunkt", MultiLineString: "Multilinje", MultiPolygon: "Multiflate", GeometryCollection: "Geometrisamling", None: "Ingen geometri" },
    export: {
      gpkgTitle: "GeoPackage-mal", gpkgDesc: "Generer en tom .gpkg-fil med alle tabeller og metadata.",
      qgisTitle: "QGIS-prosjekt", qgisDesc: "Last ned en ferdig oppsatt .qgs-fil for alle lagene i modellen.",
      databricksTitle: "Databricks SQL", databricksDesc: "Generer SQL-skript for Delta-tabeller i Databricks.",
      cloudSqlTitle: "Cloud SQL (PostGIS)", cloudSqlDesc: "Generer SQL-skript for PostgreSQL med PostGIS-utvidelse.",
      pygeoapiTitle: "pygeoapi-konfigurasjon", pygeoapiDesc: "Generer samlingskonfigurasjon for pygeoapi-config.yml.",
      docTitle: "Dokumentasjon", docDesc: "Generer en komplett dataspesifikasjon i Markdown-format.",
      download: "Last ned",
      generating: "Genererer…",
      global: "Globale eksporter",
      perLayer: "Per lag (stil og mal)",
      qml: "QGIS-stil (.qml)",
      sld: "SLD-stil (.sld)",
      csv: "Datamal (.csv)",
      svg: "ER-diagram (.svg)",
      svgDesc: "Last ned ER-diagrammet som en redigerbar vektorfil.",
    },
    tutorials: {
      officialDocs: "Offisiell dokumentasjon",
      pygeoapi: {
        title: "Moderne web-API (pygeoapi)",
        usage: "Passer for: Utviklere som vil servere data som JSON via enkle REST-kall.",
        step1: "Hva er pygeoapi?",
        step1Desc: "En moderne Python-basert server som implementerer de nye OGC API-standardene. Den er lettvektig, godt egnet for skyløsninger og støtter datautveksling i moderne formater.\n\npygeoapi sørger for at systemene dine kan snakke sammen på tvers av plattformer uten tunge proprietære løsninger. Den støtter alt fra GeoPackage til store PostgreSQL-databaser.",
        step2: "Oppsett og datakilder",
        step2Desc: "Du kan servere data fra enten en GeoPackage (.gpkg) eller en Cloud SQL-database (PostGIS).\n\n• GeoPackage er utmerket for prototyping og mindre datasett som sjelden endres.\n• Cloud SQL anbefales for store datamengder, sanntidsoppdateringer og produksjon med flere samtidige brukere.\n\nDatakilden defineres under «providers» i konfigurasjonsfilen.",
        step3: "Konfigurasjon",
        step3Desc: "Last ned konfigurasjonsfilen (.yml) fra eksportfanen. Sjekk at «database»-feltet peker på riktig kilde (filsti til GPKG eller tilkoblingsstreng til PostGIS).\n\nNår filen er på plass, kan du starte serveren med kommandoen nedenfor. Da har du et fullverdig API kjørende lokalt eller i skyen.",
        commandLabel: "Docker-kommando:"
      },
      qgisServer: {
        title: "Karttjeneste (QGIS Server)",
        usage: "Passer for: Avansert kartografi der du vil beholde nøyaktig samme utseende som i QGIS Desktop.",
        step1: "Hva er QGIS Server?",
        step1Desc: "En kraftfull kartserver som bruker QGIS-prosjektet (.qgs) direkte som konfigurasjon. Alle farger, stiler og regler du setter opp i GeoForge, vil se nøyaktig like ut når de publiseres.\n\nDen støtter klassiske tjenester som WMS (bilder) og WFS (vektor), samt de nyeste OGC API-standardene. For stabil drift i skyen anbefales en VPS (se seksjonen om skyinstanser).",
        step2: "Sjekkliste før publisering",
        step2Desc: "Åpne prosjektet i QGIS Desktop og gå gjennom disse punktene for å sikre stabil drift:\n\n• Aktiver WMS og WFS under Prosjektegenskaper → QGIS Server.\n• Sørg for at alle lag bruker relative filstier (Prosjektegenskaper → Generelt).\n• Aktiver «OGC API – Features» for moderne JSON-tilgang.\n• Definer tittel og beskrivelse under «Service Capabilities» for korrekte metadata.",
        commandLabel: "Docker-kommando:"
      },
      cloudSql: {
        title: "Skydatabase (PostGIS)",
        usage: "Passer for: Sanntidssamarbeid, store datamengder og integrasjon mot andre fagsystemer.",
        step1: "Opprett instans",
        step1Desc: "Opprett en PostgreSQL-instans hos Google Cloud, Azure eller AWS. Dette er kjernen i dataarkitekturen din, der all informasjon lagres trygt og sentralt.\n\nEn administrert database i skyen tar seg av sikkerhetskopi, tilgangskontroll og ytelsesoptimalisering automatisk, slik at du kan fokusere på dataene.",
        step2: "Bygg tabellstruktur",
        step2Desc: "Last ned Cloud SQL-skriptet herfra. Det inneholder all logikk for å bygge tabellene og relasjonene du har designet i GeoForge.\n\nKjør først «CREATE EXTENSION postgis;» i databasen, og deretter hele skriptet for å opprette tabellene med riktige restriksjoner og indekser.",
        commandLabel: "Importkommando (psql):"
      },
      env: {
        title: "Kjøremiljø",
        desc: "Sørg for at maskinen din er riktig satt opp før du kjører kommandoene.",
        docker: "Docker",
        dockerDesc: "Du må ha Docker Desktop installert og kjørende. Med Docker kan du starte servere (containere) uten å installere Python, QGIS eller databaser lokalt.",
        terminal: "Terminal",
        terminalDesc: "Bruk en moderne terminal: Terminal (Mac/Linux) eller PowerShell/WSL (Windows). Det er her du kjører Docker-kommandoene.",
        paths: "Filstier og mapper",
        pathsDesc: "Åpne terminalen i mappen der du har lagret de eksporterte filene. Bruk «cd»-kommandoen for å navigere til riktig sted før du kjører Docker-kommandoene."
      },
      hosting: {
        title: "Skyinstans og hosting",
        desc: "Når du er klar for produksjon, bør du flytte løsningen fra din egen maskin til skyen. Her er de beste alternativene for uavhengig og skalerbar drift.",
        vpsTitle: "Full kontroll (VPS)",
        vpsDesc: "Det mest fleksible valget, spesielt godt egnet for QGIS Server. Du får en dedikert Linux-server (f.eks. Ubuntu) der du installerer Docker og styrer alt selv.\n\nEn VPS gir nok ressurser til å håndtere tunge kartoppgaver og store datamengder effektivt.",
        vpsOptions: "Anbefalinger: Hetzner Cloud (best pris/ytelse i Europa), DigitalOcean (brukervennlig), Linode.",
        paasTitle: "Serverless",
        paasDesc: "Ideelt for pygeoapi. Du betaler kun når noen faktisk bruker API-et ditt, og trenger ikke vedlikeholde en server – bare last opp containeren.\n\nPasser perfekt for API-er med varierende trafikk.",
        paasOptions: "Anbefalinger: Google Cloud Run (svært skalerbart), Azure Container Apps.",
        managedDbTitle: "Administrert database",
        managedDbDesc: "For PostGIS-tabellene dine. Leverandøren håndterer sikkerhetsoppdateringer og sikkerhetskopi døgnet rundt, slik at dataene alltid er tilgjengelige.",
        managedDbOptions: "Anbefalinger: Google Cloud SQL (integrert med GIS), DigitalOcean Managed Database (enkel prismodell)."
      }
    }
  },
  en: {
    appTitle: "GeoForge", 
    appSubtitle: "From data to service",
    newModel: "New model", models: "Models", noModels: "No models yet",
    noModelsHint: "Create a new model to get started",
    landing: {
      title: "What would you like to do?",
      subtitle: "Choose a starting point",
      publishTitle: "Publish data",
      publishDesc: "Upload a GeoPackage and publish with metadata. The fastest path from file to service.",
      publishDropHint: "Drop a .gpkg file here",
      publishBrowse: "or browse",
      modelTitle: "Work with model",
      modelDesc: "Design or import a data model. For full control over structure and fields.",
      modelNew: "New empty model",
      modelImportFile: "Import file",
      modelImportGithub: "Fetch from GitHub",
      existingModels: "Or continue with an existing model:",
      parsing: "Reading file…",
    },
    quickPublish: {
      backToStart: "Back to start",
      step1Title: "Here's what we found",
      step1Desc: "Select which tables to publish.",
      tableLabel: "Table",
      features: "features",
      columns: "columns",
      step2Title: "Describe your dataset",
      step2Desc: "Add metadata so others can find and understand the data.",
      step3Title: "Publish",
      step3Desc: "Push to GitHub to start deployment.",
      publishGuideTitle: "How does publishing work?",
      publishGuideSteps: [
        "Your files are pushed to a GitHub repository that you choose below.",
        "If you're publishing to someone else's repo (e.g. The Norwegian Mapping Authority), a pull request is created automatically and must be approved before anything happens.",
        "Once the changes are merged, the service is built and deployed automatically via GitHub Actions.",
        "You need a Personal Access Token (PAT) from your own GitHub account. If publishing to someone else's repo, they must first grant your user write access (collaborator). Create your PAT at github.com → Settings → Developer settings."
      ],
      next: "Next",
      back: "Back",
      skipToPublish: "Skip to publish",
      editModel: "View full model",
      selectedLayers: "tables selected",
    },
    importGis: "Import GIS file", importGisHint: "Select a GeoJSON, GML or GPKG file",
    importUrl: "Fetch from API (URL)", importUrlHint: "Paste a link to a GeoJSON REST API",
    urlPlaceholder: "https://api.example.com/data.geojson",
    fetchUrl: "Fetch data", fetchError: "Could not fetch data. Check URL and CORS settings.",
    importGisError: "Could not read the file. Please check that the format is valid.",
    properties: "Properties", addProperty: "Add field", addSubProperty: "Add sub-field",
    sharedTypes: "Shared Types", addSharedType: "New type", sharedTypeName: "Type name",
    modelName: "Model name", modelNamePlaceholder: "e.g. Protected areas",
    descriptionPlaceholder: "Describe the contents of this dataset...",
    sharedTypeDescriptionPlaceholder: "Describe what this type is used for (e.g., common address fields)...",
    namespace: "Namespace", namespacePlaceholder: "e.g. no.agency.project",
    version: "Version", cancel: "Cancel", delete: "Delete",
    confirmDelete: "Are you sure you want to permanently delete this model?",
    confirmDeleteTitle: "Confirm Deletion",
    confirmDeleteBtn: "Yes, delete model",
    undo: "Undo", redo: "Redo",
    layers: "Layers", addLayer: "New layer", deleteLayer: "Delete layer",
    layerName: "Layer name", layerNamePlaceholder: "e.g. Protected areas",
    geomColumnName: "Geometry column",
    propName: "Field name", propNamePlaceholder: "e.g. protection_type",
    propTitle: "Display name", propTitlePlaceholder: "e.g. Protection type",
    propType: "Data type", propRequired: "Required",
    propDefault: "Default value",
    propDefaultPlaceholder: "e.g. 0, 'Unknown' or true",
    propDescription: "Description", propDescriptionPlaceholder: "What does this field describe?",
    propTargetLayer: "Target layer",
    propRelationType: "Relation type",
    propCascadeDelete: "Cascade delete (auto-delete when target is removed)",
    deploy: {
      title: "Deploy",
      subtitle: "Connect to data source and generate deploy kit",
    },
    relationGroups: {
      standard: "Database link",
      spatial: "Spatial link (auto-calculated)"
    },
    relationTypes: {
      foreign_key: "Foreign key (reference by ID)",
      intersects: "Intersects (overlaps)",
      contains: "Contains",
      within: "Is within",
      touches: "Touches",
      crosses: "Crosses"
    },
    propCodelistMode: "Value source",
    propCodelistModeInline: "Inline values",
    propCodelistModeExternal: "External URL",
    propCodelistUrl: "Codelist URL", propCodelistUrlPlaceholder: "https://...",
    propGeometryType: "Geometry type",
    codelistValues: "Code values", addValue: "Add value",
    codeKey: "Code", codeLabel: "Display name",
    codeDescription: "Description (optional)",
    schemaPreview: "JSON Schema", copySchema: "Copy", copied: "Copied!",
    noPropertiesYet: "No properties yet",
    noPropertiesHint: "Add properties to describe the layer",
    modelDetails: "Model details", language: "Language",
    unsavedChanges: "Unsaved changes",
    layerValidation: {
      title: "Validation Rules",
      addRule: "Add rule",
      field1: "Field 1",
      operator: "Operator",
      field2: "Field 2",
      errorMessage: "Error message",
      errorMessagePlaceholder: "e.g. End date must be after start date",
      deleteRule: "Delete rule",
      noRules: "No validation rules defined yet."
    },
    visualTab: "View", schemaTab: "Schema", githubTab: "GitHub", exportTab: "Export", tutorialTab: "API",
    helpTab: "Help",
    mappingTab: "Data Mapper",
    viewDiagram: "ER diagram", viewCard: "Data card",
    noPropsViz: "Add properties to see the visualization",
    moveUp: "Move up", moveDown: "Move down",
    crsLabel: "CRS",
    crsPlaceholder: "e.g. EPSG:4326",
    tabs: { models: "Models", editor: "Edit", preview: "Preview" },
    review: {
      reviewChanges: "Review changes",
      exitReview: "Exit review",
      summaryTitle: "Change summary",
      changes: "changes",
      added: "Added",
      modified: "Modified",
      deleted: "Deleted",
      empty: "empty",
      addedCode: "New code",
      deletedCode: "Deleted code",
      breakingChanges: "Breaking changes",
      newFeatures: "New features",
      improvementsFixes: "Improvements & fixes",
      modelMetadata: "Model metadata",
      compareWith: "Compare with…",
      noChanges: "No changes detected.",
      reviewingChanges: "Reviewing changes",
      totalOperations: "total operations detected",
      layer: "Layer",
      field: "Field",
      setting: "Setting",
      latestBaseline: "Latest published version",
      reviewAndPublish: "Review & publish",
      vcs: "Version control",
      currentVersion: "Current version",
      suggestedVersion: "Suggested next version",
      generatedChangelog: "Generated changelog",
      commitMessage: "Commit message",
      confirmAndPublish: "Confirm & publish",
      addedRule: "New rule",
      deletedRule: "Deleted rule",
      modifiedRuleLogic: "Modified rule logic",
      rule: "Rule",
      errorMessage: "Error message"
    },
    manual: {
      title: "User Guide",
      subtitle: "Learn how to use GeoForge step by step.",
      step1Title: "1. Design & Architecture",
      step1Desc: "Start by defining your layers. Each layer represents a table. Add properties and choose the correct data type. Use 'Codelist' for fields that should have predefined choices – this ensures machine-readable and consistent data.",
      step2Title: "2. Quality Assurance (Constraints)",
      step2Desc: "Click the shield icon on a property to set data requirements. Here you can define primary keys, enforce unique values, or set numerical limits (min/max). This is the foundation of good data quality.",
      step3Title: "3. GitHub & Collaboration",
      step3Desc: "Use the GitHub tab to store your model in a central repository. Because models are saved as plain text (JSON), you get full version control, change history, and the ability to collaborate securely with your team.",
      step4Title: "4. Reuse Data with Data Mapper",
      step4Desc: "Already have data in another format? Use the Data Mapper (🔗). Upload your source file and map the old fields to your new model to generate a ready-to-use migration script.",
      step5Title: "5. Symbology & Visualization",
      step5Desc: "Under the 'Symbology' tab you can set colors and styles. With categorized rendering, you can color data based on your codelists. These styles are automatically included when you export.",
      step6Title: "6. Distribution (Deploy)",
      step6Desc: "When your model and data are ready, go to the 'Deploy' tab. Select your data source and download a complete kit. The kit includes a Docker setup that automatically launches pygeoapi for modern REST access and QGIS Server for fully styled WMS maps."
    },
    mapper: {
      title: "Data Mapper (GDAL/OGR)",
      desc: "Migrate existing data into your model to ensure correct format and high quality.",
      intro: "Move data from existing files (GeoJSON, GeoPackage, GML) into your new data model. Map source fields to model fields and generate an ogr2ogr script to perform the transformation.",
      step1: "1. Upload source",
      step2: "2. Select tables",
      step3: "3. Map fields",
      step4: "4. Generate script",
      uploadSource: "Upload source file",
      uploadUrl: "Paste API URL",
      uploadHint: "GeoPackage, GML or GeoJSON",
      selectSourceLayer: "Source table",
      selectTargetLayer: "Target layer",
      sourceFields: "Source fields",
      targetFields: "Model fields",
      unmapped: "Unmapped",
      generateScript: "Generate script",
      copyScript: "Copy script",
      scriptHint: "The script uses ogr2ogr to transform the data.",
      sourceFilePlaceholder: "source.gpkg",
      noFieldsFound: "No fields found.",
      autoMap: "Auto-map",
      clear: "Clear",
      howToRun: "How to run the script?",
      howToRunDesc: "Once you've finished mapping fields, copy the command and run it in your terminal.",
      requirements: "Requires GDAL.",
      gdalLink: "GDAL installation",
      multiLayerHint: "You can map multiple layers in the same session.",
      explanation: {
        title: "Explanation",
        f: "-f GPKG: Saves as GeoPackage.",
        nln: "-nln: Sets the table name in the output file.",
        nlt: "-nlt: Validates and enforces the geometry type.",
        sql: "-sql: Maps old field names to new ones."
      },
      aboutGdal: {
        title: "What is GDAL/OGR?",
        desc: "GDAL/OGR is the industry standard for reading and writing geospatial data. This tool generates an ogr2ogr script that lets you move data seamlessly between systems without quality loss."
      },
      mapValues: "Map values",
      values: "values",
      keepValue: "— Keep original value —",
      noPropsTarget: "No properties defined in the target layer.",
      mapOneHint: "Map at least one layer to see the script",
      dbMigration: "Database migration",
      scalableArch: "Scalable architecture",
      simpleFileMig: "Simple file migration",
      postgisAdvantage: "Migrating to PostGIS offers the best performance for large datasets and production environments.",
      gpkgAdvantage: "GeoPackage is ideal for archiving and smaller projects."
    },
    deploy: {
      title: "Deploy",
      subtitle: "Connect to data source and publish service configuration",
      steps: ["Choose source", "Connect", "Map layers", "Publish"],
      sourceTitle: "Where is the data you want to publish?",
      sources: {
        postgis: "Cloud SQL / PostGIS",
        postgisDesc: "Google Cloud SQL, Azure, AWS RDS, or any PostgreSQL with PostGIS",
        supabase: "Supabase",
        supabaseDesc: "Connect directly via Supabase project URL and API key",
        databricks: "Databricks",
        databricksDesc: "Delta tables via Databricks SQL Warehouse",
        geopackage: "Local GeoPackage",
        geopackageDesc: "Serve data directly from a local .gpkg file without a database",
      },
      connectionTitle: "Connection details",
      fields: {
        host: "Host",
        port: "Port",
        database: "Database",
        user: "User",
        password: "Password",
        schema: "Schema",
        projectUrl: "Project URL",
        anonKey: "Anon Key",
        serverHostname: "Server Hostname",
        httpPath: "HTTP Path",
        accessToken: "Access Token",
        catalog: "Catalog",
      },
      supabaseHint: "Find this in Supabase Dashboard → Settings → API",
      mappingTitle: "Map layers to tables",
      mappingDesc: "Confirm table names and select timestamp column for change tracking.",
      sourceTable: "Source table",
      sourceTableHint: "Table name as it exists in the source database",
      timestampColumn: "Timestamp column",
      timestampPlaceholder: "e.g. updated_at, last_modified",
      timestampHint: "Optional. Without this, only inserts and deletes are tracked, not updates to existing features.",
      primaryKeyColumn: "Primary key",
      primaryKeyHint: "Column that uniquely identifies each row. Default: fid",
      fieldMapping: "Field mapping",
      moreFields: "more fields",
      // Step 3: Publish
      publishTitle: "Publish to GitHub",
      publishDesc: "Push service configuration to a GitHub repo. A CI/CD pipeline handles the rest.",
      githubRepo: "Repository",
      githubRepoPlaceholder: "organization/repo",
      githubRepoHint: "Your own repo for self-hosting, or the host organization's repo",
      githubBranch: "Branch",
      githubToken: "Personal Access Token",
      githubTokenHint: "Requires 'repo' scope",
      githubBasePath: "Path in repo",
      githubBasePathPlaceholder: "services/my-dataset",
      githubBasePathHint: "Optional subdirectory. Empty = repo root.",
      repoChecking: "Checking access…",
      repoAccessPR: "Publishing to {owner}'s repo — changes will be submitted as a pull request for review.",
      repoAccessDirect: "You have push access — changes will be pushed directly to {branch}.",
      repoAccessError: "Could not verify access. Check repo and token.",
      gpkgFilename: "GeoPackage Filename",
      gpkgHint: "Place this file in the ./data folder",
      notConnected: "Not connected",
      timestampExplainer: "Select the column storing the modification time (e.g., 'updated_at'). This enables incremental synchronization (Delta), ensuring only modified data is exported.",
      noTimestamp: "-- None (Full export) --",
      publishBtn: "Publish",
      publishing: "Publishing…",
      publishSuccess: "Published!",
      publishError: "Publish failed",
      prCreated: "Pull request created",
      prCreatedDesc: "A maintainer can now review and merge to trigger deployment.",
      directPushDesc: "Changes pushed. GitHub Actions will start deployment automatically.",
      viewPR: "Open pull request",
      viewCommit: "View commit",
      downloadZip: "Download as zip instead",
      // Shared
      kitTitle: "Deploy configuration for",
      readyToGenerate: "Ready to publish",
      source: "Source",
      layersLabel: "Layers",
      changeTracking: "Change tracking",
      changeTrackingAll: "Inserts + deletes: all layers",
      updatesLabel: "Updates",
      packageContents: "Files to publish",
      files: {
        docker: "Runs pygeoapi + QGIS Server + delta worker",
        dockerfile: "Container image for pygeoapi",
        pygeoapi: "OGC API configuration",
        pygeoapiPg: "PostgreSQL connection (live)",
        pygeoapiGpkg: "GeoPackage file (Databricks)",
        qgis: "QGIS project with styling",
        delta: "Incremental export with delete support",
        env: "Connection credentials (don't commit to git!)",
        model: "Model definition (JSON)",
        workflow: "CI/CD pipeline for automatic deployment",
      },
      previewConfig: "Preview pygeoapi config",
      back: "Back",
      next: "Next",
    },
    metadata: {
      sectionTitle: "Publishing metadata",
      sectionHint: "Structured metadata (GeoDCAT-AP) included in service configuration and catalogue registration.",
      contactName: "Contact person",
      contactNamePlaceholder: "e.g. Jane Smith",
      contactEmail: "Email",
      contactEmailPlaceholder: "e.g. jane@agency.gov",
      contactOrganization: "Publisher",
      contactOrganizationPlaceholder: "e.g. Environment Agency",
      keywords: "Keywords",
      keywordsPlaceholder: "Type a keyword and press Enter…",
      theme: "Theme (INSPIRE)",
      license: "License",
      licenses: {
        'CC-BY-4.0': "CC BY 4.0 (Attribution)",
        'CC0-1.0': "CC0 1.0 (No rights reserved)",
        'CC-BY-SA-4.0': "CC BY-SA 4.0 (Share alike)",
        'NLOD-2.0': "NLOD 2.0 (Norwegian License for Open Data)",
        'other': "Other",
      },
      accessRights: "Access rights",
      accessRightsOptions: {
        'public': "Public",
        'restricted': "Restricted",
        'non-public': "Non-public",
      },
      purpose: "Purpose",
      purposePlaceholder: "Describe the purpose of this dataset…",
      accrualPeriodicity: "Update frequency",
      frequencies: {
        'cont': "Continual",
        'daily': "Daily",
        'weekly': "Weekly",
        'monthly': "Monthly",
        'quarterly': "Quarterly",
        'annual': "Annually",
        'asNeeded': "As needed",
        'irregular': "Irregular",
        'unknown': "Unknown",
      },
      spatialExtent: "Spatial extent (bbox)",
      west: "West", east: "East", south: "South", north: "North",
      temporalExtent: "Temporal extent",
      temporalFrom: "From",
      temporalTo: "To",
      themes: {
        'ac': "Atmospheric conditions",
        'ad': "Addresses",
        'af': "Agricultural and aquaculture facilities",
        'am': "Area management / restriction zones",
        'au': "Administrative units",
        'br': "Bio-geographical regions",
        'bu': "Buildings",
        'cp': "Cadastral parcels",
        'ef': "Environmental monitoring facilities",
        'el': "Elevation",
        'er': "Energy resources",
        'ge': "Geology",
        'gg': "Geographical grid systems",
        'gn': "Geographical names",
        'hb': "Habitats and biotopes",
        'hh': "Human health and safety",
        'hy': "Hydrography",
        'lc': "Land cover",
        'lu': "Land use",
        'mf': "Meteorological / oceanographic features",
        'mr': "Mineral resources",
        'nz': "Natural risk zones",
        'of': "Oceanographic features",
        'oi': "Orthoimagery",
        'pd': "Population distribution",
        'pf': "Production and industrial facilities",
        'ps': "Protected sites",
        'rs': "Coordinate reference systems",
        'sd': "Species distribution",
        'so': "Soil",
        'sr': "Sea regions",
        'ss': "Statistical units",
        'su': "Utility and governmental services",
        'tn': "Transport networks",
        'us': "Utility and governmental services",
      },
    },
    constraints: {
      title: "Constraints",
      min: "Minimum", 
      max: "Maximum", 
      minLength: "Min length", 
      maxLength: "Max length",
      pattern: "Pattern (regex)", 
      patternPlaceholder: "^[A-Z]{3}$",
      unique: "Unique",
      primaryKey: "Primary key",
      notNull: "Required (NOT NULL)",
      enumeration: "Allowed values",
      enumPlaceholder: "Type a value and press Enter…"
    },
    styling: {
      title: "Symbology",
      modeSimple: "Simple color",
      modeCategorized: "Categorized",
      pickColor: "Pick color",
      selectProperty: "Select field for coloring",
      noCodelistProps: "No codelists found in this layer.",
      colorsForValues: "Color per value",
      followingModel: "Using model CRS:",
      pointSize: "Point size (px)",
      pointIcon: "Symbol",
      lineWidth: "Line width (px)",
      lineDash: "Line style",
      fillOpacity: "Opacity",
      hatchStyle: "Hatch pattern",
      hatchThickness: "Hatch thickness (px)",
      hatchSpacing: "Hatch spacing (px)",
      preview: "Preview",
      unitHint: "All sizes are in pixels (px).",
      icons: { circle: "Circle", square: "Square", triangle: "Triangle", star: "Star" },
      dashes: { 
        solid: "Solid", 
        dashed: "Dashed", 
        dotted: "Dotted",
        'dash-dot': "Dash-dot",
        'dash-dot-dot': "Dash-dot-dot",
        'long-dash': "Long dash"
      },
      hatches: {
        solid: "Filled",
        horizontal: "Horizontal lines",
        vertical: "Vertical lines",
        cross: "Grid",
        b_diagonal: "Diagonal (right)",
        f_diagonal: "Diagonal (left)",
        diagonal_x: "Diagonal cross"
      }
    },
    guide: {
      title: "Welcome to GeoForge",
      subtitle: "Everything you need to design, validate, and share geodata.",
      close: "Get started",
      sections: {
        modeling: "1. Design & Modeling",
        modelingDesc: "Define your layers and set up properties with precise data types. Constraints and codelists ensure your data maintains high quality from the start.",
        mapping: "2. Data Mapper",
        mappingDesc: "Reuse existing data. Connect your old source files to the new model and get ready-to-use migration scripts based on GDAL.",
        versioning: "3. GitHub & Collaboration",
        versioningDesc: "Your models are stored as text files in GitHub. This gives you full change history and makes it easy to collaborate across the organization.",
        export: "4. Build Structure (Export)",
        exportDesc: "Use the Export tab to generate table structures for your database (Cloud SQL, Databricks), empty GeoPackage templates, and clean documentation.",
        api: "5. Publish Services (Deploy)",
        apiDesc: "Once your data is ready, go to the Deploy tab. Select your data source and get a complete Docker kit that automatically launches pygeoapi (REST) and QGIS Server (WMS)!"
      }
    },
    github: {
      section: "GitHub Integration",
      persistenceDesc: "Store models in a central repository for full control and history.",
      token: "Personal Access Token",
      tokenHint: "Required to publish changes.",
      tokenHelp: "How do I create a token?",
      tokenPermissions: "The token needs the 'repo' scope to write to your repositories. This is only needed for publishing changes back to GitHub.",
      repo: "Repository",
      repoPlaceholder: "owner/repo",
      branch: "Branch",
      path: "File path",
      pathPlaceholder: "models/forestry.json",
      push: "Publish to GitHub",
      pushing: "Publishing…",
      pushed: "Published!",
      fetch: "Fetch from GitHub",
      fetching: "Fetching…",
      fetched: "Fetched!",
      error: "GitHub error",
      importError: "Could not parse the file from GitHub. Check that the file path is correct.",
      noTokenWarn: "A token is required to save changes to GitHub.",
      commitMsg: "Commit message",
      commitSummary: "Summary",
      commitMsgPlaceholder: "Describe your changes…",
      commitSummaryPlaceholder: "Short title for the change…",
      connecting: "Connecting to GitHub…",
      invalidToken: "Invalid token. Check the permissions.",
      repoNotFound: "Repository or file path not found.",
      validationFailed: "Validation failed. Is the branch correct?",
      unknownError: "An unexpected error occurred.",
      importTitle: "Import from GitHub",
      importBtn: "Fetch model"
    },
    doc: {
      title: "Data Specification",
      layer: "Layer",
      tableHeader: { name: "Name", type: "Type", req: "Required", desc: "Description" },
      yes: "Yes", no: "No"
    },
    types: { string: "Text", number: "Decimal", integer: "Integer", boolean: "Yes/No", date: "Date", geometry: "Geometry", codelist: "Codelist", json: "JSON", relation: "Relation", object: "Object (composite)", array: "Array (list)", shared_type: "Shared type" },
    geometryTypes: { Point: "Point", LineString: "LineString", Polygon: "Polygon", MultiPoint: "MultiPoint", MultiLineString: "MultiLineString", MultiPolygon: "MultiPolygon", GeometryCollection: "Geometry collection", None: "No geometry" },
    export: {
      gpkgTitle: "GeoPackage Template", gpkgDesc: "Generate an empty .gpkg file with all tables and metadata.",
      qgisTitle: "QGIS Project", qgisDesc: "Download a pre-configured .qgs file for all layers in the model.",
      databricksTitle: "Databricks SQL", databricksDesc: "Generate SQL scripts for Delta tables in Databricks.",
      cloudSqlTitle: "Cloud SQL (PostGIS)", cloudSqlDesc: "Generate SQL scripts for PostgreSQL with PostGIS extension.",
      pygeoapiTitle: "pygeoapi Config", pygeoapiDesc: "Generate collection configuration for pygeoapi-config.yml.",
      docTitle: "Documentation", docDesc: "Generate a complete data specification in Markdown format.",
      download: "Download",
      generating: "Generating…",
      global: "Global exports",
      perLayer: "Per layer (style & template)",
      qml: "QGIS Style (.qml)",
      sld: "SLD Style (.sld)",
      csv: "Data Template (.csv)",
      svg: "ER Diagram (.svg)",
      svgDesc: "Download the ER diagram as an editable vector file.",
    },
    tutorials: {
      officialDocs: "Official documentation",
      pygeoapi: {
        title: "Modern Web API (pygeoapi)",
        usage: "Best for: Developers who want to serve data as JSON via simple REST calls.",
        step1: "What is pygeoapi?",
        step1Desc: "A modern Python-based server implementing the new OGC API standards. It is lightweight, well-suited for cloud environments, and supports data exchange in modern formats.\n\npygeoapi ensures your systems can communicate across platforms without heavy proprietary solutions. It supports everything from GeoPackage to large PostgreSQL databases.",
        step2: "Setup & Data Sources",
        step2Desc: "You can serve data from either a GeoPackage (.gpkg) or a Cloud SQL (PostGIS) database.\n\n• GeoPackage is excellent for prototyping and smaller datasets that rarely change.\n• Cloud SQL is recommended for large data volumes, real-time updates, and production environments with multiple concurrent users.\n\nThe data source is defined under 'providers' in the configuration file.",
        step3: "Configuration",
        step3Desc: "Download the config file (.yml) from the Export tab. Ensure the 'database:' path points to your actual source (file path to GPKG or connection string to PostGIS).\n\nOnce the file is in place, start the server with the command below. You will then have a fully functional API running locally or in the cloud.",
        commandLabel: "Docker command:"
      },
      qgisServer: {
        title: "Map Service (QGIS Server)",
        usage: "Best for: Advanced cartography where you need to maintain the exact look and feel of QGIS Desktop.",
        step1: "What is QGIS Server?",
        step1Desc: "A high-performance map server that uses your QGIS project (.qgs) directly as configuration. All colors, styles, and rules you set up in GeoForge will look exactly the same when published.\n\nIt supports classic services like WMS (images) and WFS (vector), as well as the latest OGC API standards. For stable cloud operation, a VPS is highly recommended (see Cloud Instance section).",
        step2: "Pre-publishing checklist",
        step2Desc: "Open your project in QGIS Desktop and go through these points to ensure stable operation:\n\n• Enable WMS and WFS in Project Properties → QGIS Server.\n• Ensure all layers use relative file paths (Project Properties → General).\n• Enable 'OGC API – Features' for modern JSON access.\n• Define title and abstract under 'Service Capabilities' for correct metadata.",
        commandLabel: "Docker command:"
      },
      cloudSql: {
        title: "Cloud Database (PostGIS)",
        usage: "Best for: Real-time collaboration, large datasets, and integration with other systems.",
        step1: "Create instance",
        step1Desc: "Provision a PostgreSQL instance on Google Cloud, Azure, or AWS. This is the core of your data architecture, where all information is stored safely and centrally.\n\nA managed cloud database handles backups, access control, and performance optimization automatically, letting you focus on the data itself.",
        step2: "Build table structure",
        step2Desc: "Download the Cloud SQL script from here. It contains all the logic to build the tables and relationships you designed in GeoForge.\n\nFirst, run 'CREATE EXTENSION postgis;' in your database, then execute the full script to create tables with the correct constraints and indexes.",
        commandLabel: "Import command (psql):"
      },
      env: {
        title: "Execution Environment",
        desc: "Ensure your machine is properly set up before running the commands.",
        docker: "Docker",
        dockerDesc: "You need Docker Desktop installed and running. Docker lets you start servers (containers) without installing Python, QGIS, or databases locally.",
        terminal: "Terminal",
        terminalDesc: "Use a modern terminal: Terminal (Mac/Linux) or PowerShell/WSL (Windows). This is where you run the Docker commands.",
        paths: "Paths & Directories",
        pathsDesc: "Open your terminal in the directory where you saved the exported files. Use the 'cd' command to navigate to the correct location before running the Docker commands."
      },
      hosting: {
        title: "Cloud Instance & Hosting",
        desc: "When ready for production, move your solution from your local machine to the cloud. Here are the best options for independent and scalable operation.",
        vpsTitle: "Full Control (VPS)",
        vpsDesc: "The most flexible option, especially well-suited for QGIS Server. You get a dedicated Linux server (e.g., Ubuntu) where you install Docker and manage everything yourself.\n\nA VPS provides enough resources to handle heavy cartographic tasks and large data volumes efficiently.",
        vpsOptions: "Recommended: Hetzner Cloud (best price/performance in Europe), DigitalOcean (user-friendly), Linode.",
        paasTitle: "Serverless",
        paasDesc: "Ideal for pygeoapi. You only pay when someone actually uses your API, with no servers to maintain – just upload your container.\n\nPerfect for APIs with varying traffic patterns.",
        paasOptions: "Recommended: Google Cloud Run (highly scalable), Azure Container Apps.",
        managedDbTitle: "Managed Database",
        managedDbDesc: "For your PostGIS tables. The provider handles security updates and backups 24/7, so your data is always available.",
        managedDbOptions: "Recommended: Google Cloud SQL (integrated with GIS), DigitalOcean Managed Database (simple pricing)."
      }
    }
  }
};

export const COLORS = {
  primary: "#6366F1", // Indigo 500
  primaryDark: "#4338CA", // Indigo 700
  primaryLight: "#EEF2FF", // Indigo 50
  blue: "#1A4B8C",
  blueLight: "#E6F0FA",
  green: "#1B6B4A",
  amber: "#D97706",
  danger: "#DC2626",
};

export const TYPE_CONFIG = {
  string: { color: "#3B82F6", bg: "#EFF6FF", icon: "Aa" },
  number: { color: "#F59E0B", bg: "#FEF3C7", icon: "#" },
  integer: { color: "#F59E0B", bg: "#FEF3C7", icon: "#" },
  boolean: { color: "#A855F7", bg: "#F3E8FF", icon: "⊙" },
  date: { color: "#10B981", bg: "#ECFDF5", icon: "▦" },
  geometry: { color: COLORS.primary, bg: COLORS.primaryLight, icon: "◈" },
  codelist: { color: "#0EA5E9", bg: "#E0F2FE", icon: "≡" },
  json: { color: "#6366F1", bg: "#EEF2FF", icon: "{ }" },
  relation: { color: "#F43F5E", bg: "#FFF1F2", icon: "🔗" },
  object: { color: "#EC4899", bg: "#FDF2F8", icon: "{...}" },
  array: { color: "#8B5CF6", bg: "#FAF5FF", icon: "[ ]" },
  shared_type: { color: "#D946EF", bg: "#FDF4FF", icon: "❖" },
};

export const uid = () => Math.random().toString(36).slice(2, 9);

export const createEmptyCodeValue = (): CodeValue => ({ 
  id: uid(), 
  code: "", 
  label: "", 
  description: "" 
});

export const createEmptyProperty = (): ModelProperty => ({
  id: uid(),
  name: "",
  title: "",
  type: "string",
  required: false,
  description: "",
  defaultValue: "",
  codelistMode: "inline",
  codelistUrl: "",
  codelistValues: [],
  constraints: {},
  subProperties: []
});

export const createEmptyLayer = (name = ""): Layer => ({
  id: uid(),
  name: name || "",
  description: "",
  properties: [],
  geometryType: "Polygon",
  geometryColumnName: "geom",
  style: {
    type: 'simple',
    simpleColor: COLORS.primary,
    categorizedColors: {},
    pointSize: 8,
    pointIcon: 'circle',
    lineWidth: 2,
    lineDash: 'solid',
    fillOpacity: 0.5,
    hatchStyle: 'solid',
    hatchThickness: 1,
    hatchSpacing: 6
  }
});

export const createEmptySharedType = (name = ""): SharedType => ({
  id: uid(),
  name: name || "Ny Type",
  description: "",
  properties: []
});

export const createEmptyModel = (): DataModel => ({
  id: uid(),
  name: "",
  namespace: "",
  description: "",
  version: "1.0.0",
  layers: [createEmptyLayer("Lag 1")],
  sharedTypes: [],
  crs: "EPSG:4326",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
});